<template>
  <div class="spinner-wrapper">
    <div class="loadingio-spinner-rolling-rgq6qa9hej"><div class="ldio-eqzb3pxizm9">
      <div></div>
    </div></div>

  </div>
</template>

<script>
export default {}
</script>

<style lang="scss" scoped>

.spinner {
  &-wrapper {
    background-color: rgba(0, 0, 0, .3);
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    display: flex;
    justify-content: center;
    align-items: center;
  }
}

@keyframes ldio-eqzb3pxizm9 {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-eqzb3pxizm9 div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #17a2b8;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-eqzb3pxizm9 div {
  animation: ldio-eqzb3pxizm9 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-rgq6qa9hej {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-eqzb3pxizm9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-eqzb3pxizm9 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>